apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-demo
  description: Terraform 101 Workshop Docs + Boilerplate
  labels:
    license: MIT
spec:
  type: website
  lifecycle: experimental
  owner: cds-snc
